version: '3'
services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    image: ghcr.io/railwayapp/nixpacks:latest
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    command: "nixpacks build . && yarn dev"
    depends_on:
      - backend