### Get State
GET http://localhost:8080/state

### Post Events
POST http://localhost:8080/event
Origin: http://localhost:3000
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Content-Type: application/json

{
  "event": "Racket",
  "side": "Left"
}

### Post Input
POST http://localhost:8081/input
Origin: http://localhost:3000
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Content-Type: application/json

{
  "action": "Reset",
  "side": "Left"
}