### Get repository tree
GET https://api.github.com/repos/osklars/bit-tennis/git/trees/main
Accept: application/vnd.github.v3+json

### Get specific folder tree
GET https://api.github.com/repos/osklars/bit-tennis/contents?ref=main
Accept: application/vnd.github.v3+json

### Github rate limit
GET https://api.github.com/rate_limit
Accept: application/vnd.github.v3+json
